import path from "node:path"

/**
 * Root directory of the package
 */
export const root = new URL(`..`, import.meta.url).pathname
/**
 * Static assets for the docs' website
 * @see https://vitejs.dev/guide/assets.html
 */
export const publicDir = path.join(root, `public`)
export const openAPISpec = path.join(publicDir, `spec.json`)

/**
 * Directory w/ built (output) files
 */
export const build = path.join(root, `build`)
/**
 * Files generated by custom processing
 */
export const buildCustom = path.join(build, `custom`)
