import * as helpers from "@gracecares-ai/data-schema/src/helpers"

const nanoIdLength = 21

export const setNamePostfix = <v extends string>(v: v) => `${v}ID` as const

export const safeCharacters = `0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz`

export const regex: DataSchema.ValidationRegExp[] = [
  ...helpers.hasLengths(1, 200),

  /**
   * @todo add variant for task id and then uncomment below to use it for other ids
   */
  // helpers.hasLength(nanoIdLength),

  /**
   * we won't ever display "id" validation error, reasons:
   *   - to not disclose how we generate ids
   *   - because ids are generated, so only robots or malicious users would stumble upon this error
   */
  // { msg: ``, exp: /^[\w~.-]+$/ },
]

export const definition = {
  type: `string`,
  description: `A custom unique identifier, generated by our service`,
  example: safeCharacters.substring(0, nanoIdLength),
  regex,
} satisfies OA3.Attribute
